# Generated by Django 3.2.5 on 2021-08-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_auto_20210718_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Categoria'),
        ),
    ]
